import { describe, it, expect, vi } from 'vitest'
import { createBufferPool } from '../../../src/backend/storage/buffer'
import { makeFakeSmgr, PAGE } from './_helpers'
describe('buffer', () => {
        it('reads from smgr on first pin of a (relId, forkId, blockNo) tuple', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                buffer.pin(1, 0, 0)
                expect(smgr.read).toHaveBeenCalledTimes(1)
        })
        it('returns the same frame on cache hit without calling smgr.read again', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const f1 = buffer.pin(1, 0, 0)
                const f2 = buffer.pin(1, 0, 0)
                expect(f2).toBe(f1)
        })
        it('does not call smgr.read again when the same block is pinned twice', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                buffer.pin(1, 0, 0)
                buffer.pin(1, 0, 0)
                expect(smgr.read).toHaveBeenCalledTimes(1)
        })
        it('increments pinCount by the number of pin minus unpin calls', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const f = buffer.pin(1, 0, 0)
                buffer.pin(1, 0, 0)
                buffer.pin(1, 0, 0)
                buffer.unpin(f)
                expect(f.pinCount).toBe(2)
        })
        it('writes through smgr.write on flush when the frame was unpinned dirty', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const f = buffer.pin(1, 0, 0)
                buffer.unpin(f, true)
                buffer.flush(f)
                expect(smgr.write).toHaveBeenCalledTimes(1)
        })
        it('does not write through smgr.write on flush when the frame was unpinned clean', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const f = buffer.pin(1, 0, 0)
                buffer.unpin(f, false)
                buffer.flush(f)
                expect(smgr.write).not.toHaveBeenCalled()
        })
        it('reuses one of the existing frames as victim via clock-sweep when normal pool is full', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 2, ringCount: 1, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                const b = buffer.pin(1, 0, 1)
                buffer.unpin(a)
                buffer.unpin(b)
                const c = buffer.pin(1, 0, 2)
                expect([a, b]).toContain(c)
        })
        it('rewrites the victim frame to hold the newly pinned blockNo', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 2, ringCount: 1, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                const b = buffer.pin(1, 0, 1)
                buffer.unpin(a)
                buffer.unpin(b)
                const c = buffer.pin(1, 0, 2)
                expect(c.blockNo).toBe(2)
        })
        it('issues a fresh smgr.read on cache miss after clock-sweep eviction', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 2, ringCount: 1, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                const b = buffer.pin(1, 0, 1)
                buffer.unpin(a)
                buffer.unpin(b)
                buffer.pin(1, 0, 2)
                expect(smgr.read).toHaveBeenCalledTimes(3)
        })
        it('writes a dirty victim through smgr.write during clock-sweep eviction', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 2, ringCount: 1, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                const b = buffer.pin(1, 0, 1)
                buffer.unpin(a, true)
                buffer.unpin(b, true)
                buffer.pin(1, 0, 2)
                expect(smgr.write).toHaveBeenCalled()
        })
        it('does not evict a normal pool frame when a bulk hint pin is issued', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 2, ringCount: 2, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                buffer.pin(1, 0, 1)
                buffer.pin(1, 0, 2, 'bulk_read')
                buffer.pin(1, 0, 3, 'bulk_write')
                buffer.pin(1, 0, 4, 'vacuum')
                expect(buffer.pin(1, 0, 0)).toBe(a)
        })
        it('writes every dirty frame through smgr.write on flushAll', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const a = buffer.pin(1, 0, 0)
                const b = buffer.pin(1, 0, 1)
                const c = buffer.pin(1, 0, 2, 'bulk_read')
                buffer.unpin(a, true)
                buffer.unpin(b, true)
                buffer.unpin(c, true)
                buffer.flushAll()
                expect(smgr.write).toHaveBeenCalledTimes(3)
        })
        it('exposes a bytes buffer of length pageSize on each pinned frame', () => {
                const smgr = makeFakeSmgr()
                const buffer = createBufferPool({ smgr, frameCount: 4, ringCount: 2, pageSize: PAGE })
                const f = buffer.pin(1, 0, 0)
                expect(f.bytes.length).toBe(PAGE)
        })
})
